In [40]:
##ADD ALL IMPORTS HERE FOR ALL CELLS##

import pandas as pd
import numpy as np

In [75]:
PM25 = pd.read_csv("PM2.5.csv",
    skiprows=4,
    encoding="utf-8-sig")

PrimarySchoolGross = pd.read_csv('Primary_School_Enrollment_%Gross.csv',
    skiprows=4,
    encoding="utf-8-sig")

LifeExpectancy = pd.read_csv('Life_Expectancy.csv',
    skiprows=4,
    encoding="utf-8-sig")

GDPperCap = pd.read_csv('GDP_PCAP.csv',
    skiprows=4,
    encoding="utf-8-sig")

ForestArea = pd.read_csv('Forest_Area.csv',
    skiprows=4,
    encoding="utf-8-sig")

EnergyUse = pd.read_csv('EnergyUseData.csv',
    skiprows=4,
    encoding="utf-8-sig")

ExportofGnS = pd.read_csv('ExportofGoodandService.csv',
    skiprows=4,
    encoding="utf-8-sig")

RenewableElectricty = pd.read_csv('RenewableElectricyOutput.csv',
    skiprows=4,
    encoding="utf-8-sig")

WomenParliament = pd.read_csv('ProportionWomeninParliamnet.csv',
    skiprows=4,
    encoding="utf-8-sig")

PopulationDensity = pd.read_csv('PopulationDensity.csv',
    skiprows=4,
    encoding="utf-8-sig")

LivestockProduction = pd.read_csv('LivestockProductionIndex.csv',
    skiprows=4,
    encoding="utf-8-sig")


Datasets = {'PM25': PM25, 'PrimarySchoolGross' : PrimarySchoolGross, 
            'LifeExpectancy' : LifeExpectancy, 'GDPperCap':GDPperCap, 'ForestArea':ForestArea, 
            'EnergyUse':EnergyUse, 'ExportofGnS':ExportofGnS, 'RenewableElectricty':RenewableElectricty, 
            'WomenParliament':WomenParliament, 'PopulationDensity':PopulationDensity, 
            'LivestockProduction':LivestockProduction}


new_df = {}
for name, df in Datasets.items():
    temp = df.melt(
        id_vars=['Country Name', 'Country Code', 'Indicator Name'],
        var_name='Year',
        value_name=name)
    
    temp = temp[temp['Year'].between('2000','2020')]
    temp['Year'] = temp['Year'].astype(int)
    new_df[name] = temp[['Country Name', 'Country Code', 'Year', name]]

fullset = new_df['PM25']

for name, df in new_df.items():
    if name != 'PM25':
        fullset = fullset.merge(df, on=['Country Name', 'Country Code', 'Year'], how='left')

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,28.877274,27.311377,27.404295,26.248200,26.755686,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,72.765910,65.862347,67.227177,58.330872,46.087094,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,62.894132,60.344618,56.099951,50.771962,54.891820,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,25.180701,23.959151,24.265015,24.598811,25.145238,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,"Yemen, Rep.",YEM,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,40.724117,42.120481,43.910348,41.640793,34.832360,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,24.147689,23.754937,23.812250,23.189772,23.753069,NaN,NaN,NaN,NaN,NaN
264,Zambia,ZMB,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,26.165910,23.758282,23.336720,23.203748,24.308592,NaN,NaN,NaN,NaN,NaN
265,Zimbabwe,ZWE,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,22.570698,17.997754,19.112099,18.528607,19.494180,NaN,NaN,NaN,NaN,NaN

In [76]:
fullset.to_csv('fullset.csv', index = False)
fullset['Country Code'].unique()

array(['ABW', 'AFE', 'AFG', 'AFW', 'AGO', 'ALB', 'AND', 'ARB', 'ARE',
       'ARG', 'ARM', 'ASM', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL',
       'BEN', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLR', 'BLZ',
       'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN', 'BWA', 'CAF', 'CAN',
       'CEB', 'CHE', 'CHI', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG',
       'COL', 'COM', 'CPV', 'CRI', 'CSS', 'CUB', 'CUW', 'CYM', 'CYP',
       'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'EAP', 'EAR',
       'EAS', 'ECA', 'ECS', 'ECU', 'EGY', 'EMU', 'ERI', 'ESP', 'EST',
       'ETH', 'EUU', 'FCS', 'FIN', 'FJI', 'FRA', 'FRO', 'FSM', 'GAB',
       'GBR', 'GEO', 'GHA', 'GIB', 'GIN', 'GMB', 'GNB', 'GNQ', 'GRC',
       'GRD', 'GRL', 'GTM', 'GUM', 'GUY', 'HIC', 'HKG', 'HND', 'HPC',
       'HRV', 'HTI', 'HUN', 'IBD', 'IBT', 'IDA', 'IDB', 'IDN', 'IDX',
       'IMN', 'IND', 'INX', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA',
       'JAM', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA',
       'KOR', 'KWT', 'LAC', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LCN',
       'LDC', 'LIC', 'LIE', 'LKA', 'LMC', 'LMY', 'LSO', 'LTE', 'LTU',
       'LUX', 'LVA', 'MAC', 'MAF', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV',
       'MEA', 'MEX', 'MHL', 'MIC', 'MKD', 'MLI', 'MLT', 'MMR', 'MNA',
       'MNE', 'MNG', 'MNP', 'MOZ', 'MRT', 'MUS', 'MWI', 'MYS', 'NAC',
       'NAM', 'NCL', 'NER', 'NGA', 'NIC', 'NLD', 'NOR', 'NPL', 'NRU',
       'NZL', 'OED', 'OMN', 'OSS', 'PAK', 'PAN', 'PER', 'PHL', 'PLW',
       'PNG', 'POL', 'PRE', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'PSS',
       'PST', 'PYF', 'QAT', 'ROU', 'RUS', 'RWA', 'SAS', 'SAU', 'SDN',
       'SEN', 'SGP', 'SLB', 'SLE', 'SLV', 'SMR', 'SOM', 'SRB', 'SSA',
       'SSD', 'SSF', 'SST', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ',
       'SXM', 'SYC', 'SYR', 'TCA', 'TCD', 'TEA', 'TEC', 'TGO', 'THA',
       'TJK', 'TKM', 'TLA', 'TLS', 'TMN', 'TON', 'TSA', 'TSS', 'TTO',
       'TUN', 'TUR', 'TUV', 'TZA', 'UGA', 'UKR', 'UMC', 'URY', 'USA',
       'UZB', 'VCT', 'VEN', 'VGB', 'VIR', 'VNM', 'VUT', 'WLD', 'WSM',
       'XKX', 'YEM', 'ZAF', 'ZMB', 'ZWE'], dtype=object)

In [79]:
noncountries = [
'AFE','AFW','ARB','CEB','CSS','EAP','EAR','EAS','ECA','ECS',
'EMU','EUU','FCS','HIC','HPC','IBD','IBT','IDA','IDB','IDX',
'INX','LAC','LCN','LDC','LIC','LMC','LMY','MEA','MIC','MNA',
'NAC','OED','OSS','PRE','PSS','PST','SAS','SSA','SSF','SST',
'TEA','TEC','TLA','TMN','TSA','TSS','UMC','WLD'
]

fullset = fullset[~fullset['Country Code'].isin(noncountries)]

fullset

,Country Name,Country Code,Year,PM25,PrimarySchoolGross,LifeExpectancy,GDPperCap,ForestArea,EnergyUse,ExportofGnS,RenewableElectricty,WomenParliament,PopulationDensity,LivestockProduction
0,Aruba,ABW,2000,NaN,NaN,70.149,20681.023027,2.333333,NaN,74.386011,0.0,NaN,503.266667,NaN
2,Afghanistan,AFG,2000,64.76728,21.45785,53.463,174.930991,1.852782,NaN,NaN,93.537318,NaN,30.863847,98.12
4,Angola,AGO,2000,23.509342,NaN,43.963,563.733796,62.331443,428.222669,NaN,62.303806,15.454545,12.990189,67.62
5,Albania,ALB,2000,22.265189,NaN,71.804,1160.420471,28.076642,581.374749,19.530471,96.149016,5.16129,112.738212,80.43
6,Andorra,AND,2000,16.221599,NaN,79.353,21810.250381,34.042553,NaN,NaN,100.0,7.142857,139.755319,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5581,Kosovo,XKX,2020,NaN,NaN,71.865,4310.889638,NaN,NaN,21.695147,5.417612,NaN,NaN,NaN
5582,"Yemen, Rep.",YEM,2020,34.83236,NaN,63.33,NaN,1.039832,77.5877,NaN,19.083653,0.332226,68.441129,113.62
5583,South Africa,ZAF,2020,23.753069,101.300343,62.174,5580.603831,14.055091,2037.461942,27.575914,6.011915,46.75,49.924063,104.49
5584,Zambia,ZMB,2020,24.308592,NaN,60.731,951.644317,60.283337,759.022718,46.720186,85.554717,16.766467,25.638487,105.97
5585,Zimbabwe,ZWE,2020,19.49418,93.612586,59.091,2059.674454,45.093912,373.557246,18.931225,60.785554,31.851852,40.136714,105.66