In [7]:
import pandas as pd

# Read file (skip metadata rows at top)
df = pd.read_csv(
    "API_EN.ATM.PM25.MC.M3_DS2_en_csv_v2_262.csv",
    skiprows=4,     # skips "Data Source", "Last Updated", etc.
    na_values=[","],  # treat "," as missing values
)
df.head(3)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,28.877274,27.311377,27.404295,26.248200,26.755686,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,72.765910,65.862347,67.227177,58.330872,46.087094,NaN,NaN,NaN,NaN,NaN

In [11]:
df = df.dropna(axis=1, how="all")  # remove empty year columns
df = df.dropna(subset=["Country Name"])  # keep valid countries

In [13]:
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,ABW,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,25.111399,24.547886,24.155248,23.906832,23.753597,23.721569,...,29.449472,29.908441,29.070582,27.779344,29.515468,28.877274,27.311377,27.404295,26.248200,26.755686
2,Afghanistan,AFG,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,64.174097,64.188153,64.210526,64.244141,64.291923,64.356800,...,61.817056,70.922317,73.131816,77.143728,73.490818,72.765910,65.862347,67.227177,58.330872,46.087094
3,Africa Western and Central,AFW,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,60.240684,58.514553,57.243345,56.402812,55.947741,55.816673,...,54.189720,58.213217,46.959269,47.135125,71.295051,62.894132,60.344618,56.099951,50.771962,54.891820
4,Angola,AGO,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,23.831767,23.443967,23.129464,22.895329,22.748636,22.696458,...,24.337940,24.480493,24.538658,23.945584,25.002150,25.180701,23.959151,24.265015,24.598811,25.145238